### ISSUE TITLE
Agency pages gotta use the rounded profile pics

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#13]
Agency Page:

![image](https://cloud.githubusercontent.com/assets/6335546/12834361/ceeee7c4-cb74-11e5-8f0b-8f626b3b3bd0.png)

v

People Page:
![image](https://cloud.githubusercontent.com/assets/6335546/12834374/e39e817a-cb74-11e5-9774-5c0c1211d931.png)

**Comment by paultag** [comment]
woah, how did that happen
