### ISSUE TITLE
gather seals for agencies.

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#23]
- [ ] Veterans Affairs
- [ ] Office of the President
- [ ] Homeland Security
- [ ] State
- [ ] Defense
- [ ] Justice
- [ ] IRS
- [ ] Education
- [ ] OPM
- [ ] HHS
- [ ] SSA
- [ ] SBA
- [ ] Transporation
- [ ] Interior
- [ ] Trade Reps
- [ ] Commerce
- [ ] Nasa
- [ ] PMI

**Comment by paultag** [comment]
Looks great!
