### ISSUE TITLE
Duplicate "Office of the President" agency cards

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#24]
There are two cards for office of the president under the agencies page. One has 21 DSEs, one has 0.

![image](https://cloud.githubusercontent.com/assets/6335546/12873268/af9ec4de-cd86-11e5-9499-e95d47ab3404.png)

![image](https://cloud.githubusercontent.com/assets/6335546/12873269/b4464db8-cd86-11e5-9a3f-388b550bd599.png)

**Comment by paultag** [comment]
still dupe'd - one is hq one is eop - for now, since eop is empty, it's not a big deal. closing until it's a big deal
