### ISSUE TITLE
If no GH user exists, use default profile picture

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#26]
In loadgithub.py, `expert.photo_url` is set to `github_user.avatar_url`. We should set a default photo if there is no Github User or it's ambiguous. 

```
    if expert.photo_url == "":
        expert.photo_url = github_user.avatar_url
```

If we do not, an empty `src=""` adds an extra border to the profile pic:

![image](https://cloud.githubusercontent.com/assets/6335546/12873716/aab55f3a-cd92-11e5-8f11-ac4cba3fc25c.png)

We can use the following asset:

![default-profile](https://cloud.githubusercontent.com/assets/6335546/12873719/c54df546-cd92-11e5-9c1a-21ed1b26f4e2.png)

Which ends up looking like this:

![image](https://cloud.githubusercontent.com/assets/6335546/12873722/dac4ad16-cd92-11e5-9061-505619eee981.png)

**Comment by paultag** [comment]
We should actually do that in front end template -- if there is no photo,
use the default -- this likely will live in cards/expert.html

**Comment by KHarshawat** [comment]
@paultag  Cool, I'm happy to write it ... here's what I would expect but syntax is prob wrong

```
{% if expert.photo_url == None %}
            <img class="mdl-pic" src="public/static/img/default-pic.png" />
{% else %}
            <img class="mdl-pic" src="{{expert.photo_url}}" />
{% endif %}
```

**Comment by KHarshawat** [comment]
Nvm .. got it:

```
        {% if expert.photo_url == '' %}
            <img class="mdl-pic" src="/static/img/default-pic.png" />
        {% else %}
            <img class="mdl-pic" src="{{expert.photo_url}}" />
        {% endif %}
```

**Comment by paultag** [comment]
Looks great except "" and not none - you can also put the conditional in
the middle of the IMG tag inside the href
