### ISSUE TITLE
Remove meta information when there are other indicators

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#27]
![image](https://cloud.githubusercontent.com/assets/6335546/12874456/1bf43bda-cda2-11e5-85aa-30c848fe351b.png)

In the example above the "Phone" and "Email" meta information is redundant with the icons and ends up cluttering the sidebar. While knowing that the GH and Slack handles were pulled from those locations, I don't believe it's worth including here (unless we did it in a n alt-tag or something). I do think the "Official Email" meta-tag is useful so we should keep it.

**Comment by paultag** [comment]
I'm showing `note` rather than label
