### ISSUE TITLE
Add tooltips/hover states to people's faces in projects

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#28]
Add hover-states so that when you hover over someone's face, you see their name. This is particularly helpful when that person does not have a customized GH profile pic.

![image](https://cloud.githubusercontent.com/assets/6335546/12874618/052da28a-cda5-11e5-988d-306b4393147f.png)

**Comment by paultag** [comment]
@KHarshawat have a that CSS and hTML bits somewhere?

**Comment by KHarshawat** [comment]
I'll add it to my list.
