### ISSUE TITLE
Consider changing "Office of the President" to "Headquarters"

### ISSUE THREAD

**Issue by KHarshawat** [paultag/mandelbrot#33]
I thought I'd get used to this but seeing "Office of the President" is pretty confusing since no one calls it that. "Headquarters" is probably more appropriate. Wondering if others agree.

**Comment by paultag** [comment]
https://github.com/paultag/mandelbrot/blob/master/mandelbrot/management/commands/loadpriorities.py#L53 is where the change can live :+1:

**Comment by paultag** [comment]
considered and done
