### ISSUE TITLE
Alphabetizing by first name makes my soul weep

### ISSUE THREAD

**Issue by mbellotti** [paultag/mandelbrot#46]
:mortar_board:

**Comment by paultag** [comment]
@mbellotti interesting.

So, I object, on moral and philosophical grounds, on splitting names first/last.

One of the many reasons was my code breaking, back when I cared to try, on [Frosty](http://openstates.org/mt/legislators/MTL000177/forrestina-frosty-calf-boss-ribs/) -- in particular, doing splitting on `Forrestina Frosty Calf Boss Ribs` breaks a lot of assumptions.

I'd be open to a `sort_name`, but I'm not sure how to bootstrap that data.

I have some code to do name splitting, so I guess I could grind on it. Thoughts?

**Comment by paultag** [comment]
@mbellotti I added a `sort_name` attribute to people. I bulk-imported "last names". I'll deploy once I can get back to a place I can get to my RDS from.

**Comment by paultag** [comment]
Checked that it works locally. Closing. I'll deploy soonish.
