### ISSUE TITLE
OMB M-15-13 compliance

### ISSUE THREAD

**Issue by alex** [paultag/mandelbrot#53]
teehee. for real though: HTTPS-only!

**Comment by paultag** [comment]
@alex yeah; I think this depends on a real domain; I'll go ahead and see if I can set this up "for real"

**Comment by alex** [comment]
Is there a reason not to get a letsencrypt cert for it where it is now?

**Comment by ab** [comment]
:+1: Would be much more comfortable with this over HTTPS. LMK if I can help.

**Comment by paultag** [comment]
Made a LE cert for it, gave up :)
